branch-defaults:
  default:
    environment: peakfxsite-env
    group_suffix: null
environment-defaults:
  myflask-env:
    branch: null
    repository: null
  peakfxsite-env:
    branch: null
    repository: null
global:
  application_name: peakfxsite
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
